name: Test All OS Builds

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build project
        run: mvn -B package --file pom.xml

      - name: Build EXE and MSI
        run: |
          jpackage --input target --name StockKeeper --main-jar stock-keeper-1.0-SNAPSHOT.jar --main-class com.stockkeeper.Main --icon src/main/resources/warehouse.ico --type exe --win-shortcut --win-menu --dest dist/
          jpackage --input target --name StockKeeper --main-jar stock-keeper-1.0-SNAPSHOT.jar --main-class com.stockkeeper.Main --icon src/main/resources/warehouse.ico --type msi --win-shortcut --win-menu --dest dist/

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Install Linux package tools
        run: sudo apt-get install -y rpm fakeroot

      - name: Build project
        run: mvn -B package --file pom.xml

      - name: Build DEB and RPM
        run: |
          jpackage --input target --name StockKeeper --main-jar stock-keeper-1.0-SNAPSHOT.jar --main-class com.stockkeeper.Main --icon src/main/resources/warehouse.png --type deb --dest dist/
          jpackage --input target --name StockKeeper --main-jar stock-keeper-1.0-SNAPSHOT.jar --main-class com.stockkeeper.Main --icon src/main/resources/warehouse.png --type rpm --dest dist/

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build project
        run: mvn -B package --file pom.xml

      - name: Build PKG and DMG
        run: |
          jpackage --input target --name StockKeeper --main-jar stock-keeper-1.0-SNAPSHOT.jar --main-class com.stockkeeper.Main --icon src/main/resources/a3okk-ltnpq.icns --type pkg --dest dist/
          jpackage --input target --name StockKeeper --main-jar stock-keeper-1.0-SNAPSHOT.jar --main-class com.stockkeeper.Main --icon src/main/resources/a3okk-ltnpq.icns --type dmg --dest dist/

      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/
